feat(docker):Fixed Dockerfile not respecting Pipfile.lock (#12)
The Dockerfile didnt respect Pipfile.lock which meant that Sanic would use the latest version which deprecates the ability to store data in a Request object in a dict like manner. This leads to the following error which is thrown on every request:
```
File "/root/.local/share/virtualenvs/bot-BH0CoWo9/lib/python3.7/site-packages/sanic/app.py", line 973, in handle_request
  response = await response
File "/bot/core/utils.py", line 94, in wrapper
  return await func(request, await app.db.logs.find_one({"key": key}))
File "app.py", line 78, in get_logs_file
  return log_entry.render_html()
File "/bot/core/models.py", line 63, in render_html
  return self.app.render_template("logbase", log_entry=self)
File "app.py", line 33, in render_template
  kwargs["session"] = request["session"]
TypeError: 'Request' object is not subscriptable
```